"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[mgr]
# cwd label at top left
cwd = { bold = true }
hovered = { fg = "#0f0f0f", bg = "#8f8aac" }
# line highlighted in preview window
preview_hovered = { fg = "#f0f0f0", bg = "#393939" }
find_keyword = { fg = "#0f0f0f", bg = "#aca98a", bold = true }
find_position = { fg = "#0f0f0f", bg = "#aca98a", bold = true }
marker_copied = { fg = "#778c73", bg = "#778c73" }
marker_cut = { fg = "#b36d7c", bg = "#b36d7c" }
count_copied = { fg = "#0f0f0f", bg = "#778c73" }
count_cut = { fg = "#0f0f0f", bg = "#b36d7c" }

[indicator]
padding = { open = "█", close = "█" }

[mode]
normal_main = { fg = "#767676", bg = "#393939", bold = true }
# complementary color for status blocks
normal_alt = { fg = "#767676", bg = "#0f0f0f", bold = true }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
